name: ai_nutrition_chatbot
description: A chatbot application for nutrition guidance.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.7.0
  permission_handler: ^10.4.5
  provider: ^6.1.3
  http: ^1.3.0
  speech_to_text: ^7.0.0 # Use the latest compatible version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Declare assets used in the project
  assets:
    - assets/env.json
    - assets/logo1.png
    - assets/walking.json